#!/bin/bash
cd ~/fefss
echo -e '\033[1m'

echo
echo "  FFFFFF  EEEEEE  FFFFFF   SSSSS   SSSSS "
echo "  F       E       F       S       S      "
echo "  FFFFF   EEEEEE  FFFFF    SSSS    SSSS  "
echo "  F       E       F            S       S "
echo "  F       EEEEEE  F       SSSSS   SSSSS  "
echo 
echo "  << Fast and Easy File Sharing System >>"
echo

~/fefss/menu/menu.out
mode=$?

case $mode in
  0) bash send/shell_send_desktop;;
  1) bash recv/shell_desktop;;
  2) bash data/data_add_shell;;
  3) bash data/data_del_shell;;
  4) exit 0;;
  *) echo "undefined"
     exit 1
esac
